name: Build and Release
on:
  push: 
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '8.0.x'
      
      - name: Install WiX 4 CLI
        run: dotnet tool install --global wix --version 4.0.5
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build application
        run: dotnet build --configuration Release --no-restore
      
      - name: Run tests (if any)
        run: dotnet test --no-build --configuration Release --verbosity normal
        continue-on-error: true
      
      - name: Publish self-contained application
        run: |
          dotnet publish ./src/TavernTally/TavernTally.csproj `
            -c Release `
            -f net8.0-windows `
            -o ./publish `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -p:PublishTrimmed=false
      
      - name: Create installer directory structure
        run: |
          New-Item -ItemType Directory -Force -Path "./installer-build"
          New-Item -ItemType Directory -Force -Path "./artifacts"
          Copy-Item "./publish/*" "./installer-build/" -Recurse -Force
          Copy-Item "./assets/app.ico" "./installer-build/" -Force
      
      # Skip MSI build for now due to WiX 4 complexity
      # - name: Build MSI installer
      #   run: |
      #     dotnet build ./installer/installer.wixproj `
      #       -c Release `
      #       -p:SourceDir="$(Get-Location)\installer-build" `
      #       -p:Version="1.0.${{ github.run_number }}" `
      #       -p:OutputPath="$(Get-Location)\artifacts\"
      
      - name: Create portable ZIP
        run: |
          Compress-Archive -Path "./publish/*" -DestinationPath "./artifacts/TavernTally-Portable-v1.0.${{ github.run_number }}.zip"
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TavernTally-Release-v1.0.${{ github.run_number }}
          path: |
            ./artifacts/*.zip
          retention-days: 90
      
      # Create GitHub Release for tags
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
